# Generated by Django 6.0.1 on 2026-01-22 23:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название тарифа')),
                ('multiplier', models.DecimalField(decimal_places=2, help_text='1.0, 1.5, 2.0 и т.д.', max_digits=4, verbose_name='Коэффициент')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.CharField(help_text='Введите адрес отправления', max_length=255, verbose_name='Откуда ехать')),
                ('to_address', models.CharField(help_text='Введите адрес назначения', max_length=255, verbose_name='Куда ехать')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Укажите стоимость поездки', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Стоимость')),
                ('currency', models.CharField(choices=[('BYN', 'Белорусский рубль')], default='BYN', max_length=3, verbose_name='Валюта')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтвержден'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('client', models.ForeignKey(help_text='Пользователь, создавший заказ', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.tariff', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
